"""Item-eligibility specification for the non-quiz DK measurement audit.

SPEC is the frozen record of which 2024 NFCS Investor Survey items are eligible
for the auxiliary non-quiz DK index, and why each item was kept or dropped. It
is consumed by ``05_nonquiz_dk_sensitivity.py``, which writes it out verbatim as
``docs/nonquiz-dk-item-audit.csv``.

Eligibility rule (frozen before any outcome model was run) -- an item is
INCLUDED iff, per the Investor Survey instrument and data dictionary:

  1. it is administered to every continuing respondent, verified from documented
     skip logic rather than from patterns of nonmissing data;
  2. it offers code 98 = "Don't know" as a substantive response option;
  3. it is not a quiz item, not G23, not the outcome G43, not a variable used as
     a model covariate elsewhere in the study (G2, G40, G41), and not an
     eligibility screener where selecting DK terminated the interview (A1, A3);
  4. it is not an ID, weight, or demographic.

Eligibility was determined without reference to G43 or to any outcome result.

  105 items assessed | 69 INCLUDE | 36 EXCLUDE

------------------------------------------------------------------------------
PROVENANCE -- read before relying on this file
------------------------------------------------------------------------------
This module was RECONSTRUCTED on 2026-08-25 from the committed audit table
``docs/nonquiz-dk-item-audit.csv``. The original ``audit_spec.py`` was written
in an assistant chat session and was not part of the file transfer that seeded
this repository; only its output survived.

The reconstruction is mechanical, not interpretive. The CSV is exactly
``pd.DataFrame(SPEC).to_csv(index=False)``, so inverting it recovers SPEC
exactly. The round trip is asserted at import time below: if this file and the
committed CSV ever disagree, the import fails rather than silently proceeding.

What that guarantee does and does not cover. It establishes that this file
reproduces the audit table the published sensitivity results were computed
from. It does not independently re-derive item eligibility from the survey
instrument. If the original module is recovered, diff it against this one.
"""

SPEC = [
    {
        'variable': 'NFCSID',
        'block': 'administrative',
        'construct': 'respondent ID',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'WGT1',
        'block': 'administrative',
        'construct': 'survey weight',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'S_Gender2',
        'block': 'administrative',
        'construct': 'sex',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'S_Age',
        'block': 'administrative',
        'construct': 'age band',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'S_Ethnicity',
        'block': 'administrative',
        'construct': 'ethnicity',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'S_Education',
        'block': 'administrative',
        'construct': 'education',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'S_Income',
        'block': 'administrative',
        'construct': 'household income',
        'universally_asked': 'n/a',
        'meaning_of_98': 'no 98 code',
        'dk_opportunity_type': 'none',
        'include': 'EXCLUDE',
        'reason': 'ID, weight, or demographic; not a survey response with a DK option',
    },
    {
        'variable': 'A1',
        'block': 'A: screening',
        'construct': 'investment decision role',
        'universally_asked': 'No — DK terminated the interview',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Eligibility screener: A1 in (3,98,99) terminated. Respondents who chose DK are absent by design.',
    },
    {
        'variable': 'A2',
        'block': 'A: screening',
        'construct': 'owns retirement accounts',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Asked of all continuing respondents; DK = uncertainty about own retirement holdings.',
    },
    {
        'variable': 'A3',
        'block': 'A: screening',
        'construct': 'owns non-retirement securities',
        'universally_asked': 'No — DK terminated the interview',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Eligibility screener: A3 in (2,98,99) terminated. Constant (=Yes) in the file; no DK variance possible.',
    },
    {
        'variable': 'B2_1',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns individual stocks',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_2',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns individual bonds',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_3',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns mutual funds',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_4',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns ETFs',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_5',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns annuities',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_7',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns commodities/futures',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_20',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns whole life insurance',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_21',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns REITs',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_23',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns microcap/penny stocks',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_24',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns structured notes',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B2_25',
        'block': 'B2 grid (11 rows)',
        'construct': 'currently owns private placements',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = uncertainty about own holdings. GRID — see battery weighting.',
    },
    {
        'variable': 'B30_2024',
        'block': 'B: investments',
        'construct': 'when first started investing',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot recall onset.',
    },
    {
        'variable': 'B3',
        'block': 'B: investments',
        'construct': 'trading frequency past 12 months',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot recall count.',
    },
    {
        'variable': 'B4_2024',
        'block': 'B: investments',
        'construct': 'total non-retirement portfolio value',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = does not know own balance.',
    },
    {
        'variable': 'B5',
        'block': 'B: investments',
        'construct': 'account permits margin',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = does not know own account terms.',
    },
    {
        'variable': 'B6',
        'block': 'B: investments',
        'construct': 'has purchased on margin',
        'universally_asked': 'No — asked only if B5=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (B5=1); denominator would vary across respondents.',
    },
    {
        'variable': 'B33',
        'block': 'B: investments',
        'construct': 'account permits options trading',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = does not know own account terms.',
    },
    {
        'variable': 'B34',
        'block': 'B: investments',
        'construct': 'ever purchased/sold options',
        'universally_asked': 'No — asked only if B33=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (B33=1).',
    },
    {
        'variable': 'B10',
        'block': 'B: investments',
        'construct': 'risk willingness statement',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot place own risk preference.',
    },
    {
        'variable': 'B40',
        'block': 'B: investments',
        'construct': 'agrees must take big risks',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked 1-7 agreement item.',
    },
    {
        'variable': 'B41',
        'block': 'B: investments',
        'construct': 'ever bought a meme stock',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot recall.',
    },
    {
        'variable': 'B23',
        'block': 'B: investments',
        'construct': 'heard of cryptocurrencies',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked awareness item.',
    },
    {
        'variable': 'B24',
        'block': 'B: investments',
        'construct': 'perceived crypto riskiness',
        'universally_asked': 'No — asked only if B23=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (B23=1).',
    },
    {
        'variable': 'B25',
        'block': 'B: investments',
        'construct': 'has invested in crypto',
        'universally_asked': 'No — asked only if B23=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (B23=1).',
    },
    {
        'variable': 'B26',
        'block': 'B: investments',
        'construct': 'considering crypto in future',
        'universally_asked': 'No — asked only if B25!=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (conditional on B25).',
    },
    {
        'variable': 'C22_1',
        'block': 'C22 grid (4 rows)',
        'construct': 'trading channel frequency: via a specific advisor',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own frequency. GRID — see battery weighting.',
    },
    {
        'variable': 'C22_2',
        'block': 'C22 grid (4 rows)',
        'construct': 'trading channel frequency: by calling the firm',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own frequency. GRID — see battery weighting.',
    },
    {
        'variable': 'C22_3',
        'block': 'C22 grid (4 rows)',
        'construct': 'trading channel frequency: online via website',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own frequency. GRID — see battery weighting.',
    },
    {
        'variable': 'C22_4',
        'block': 'C22 grid (4 rows)',
        'construct': 'trading channel frequency: via mobile app',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own frequency. GRID — see battery weighting.',
    },
    {
        'variable': 'C40',
        'block': 'C: accounts',
        'construct': 'worried internet makes accounts less secure',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked 1-7 agreement item.',
    },
    {
        'variable': 'C23_1',
        'block': 'C23 grid (4 rows)',
        'construct': 'pays investment advice fees',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = does not know own fee structure. GRID — see battery weighting.',
    },
    {
        'variable': 'C23_2',
        'block': 'C23 grid (4 rows)',
        'construct': 'pays trade commissions',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = does not know own fee structure. GRID — see battery weighting.',
    },
    {
        'variable': 'C23_3',
        'block': 'C23 grid (4 rows)',
        'construct': 'pays mutual fund/ETF fees',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = does not know own fee structure. GRID — see battery weighting.',
    },
    {
        'variable': 'C23_4',
        'block': 'C23 grid (4 rows)',
        'construct': 'pays account service fees',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = does not know own fee structure. GRID — see battery weighting.',
    },
    {
        'variable': 'C24',
        'block': 'C: accounts',
        'construct': 'approximate total fee percentage',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = does not know own fee level.',
    },
    {
        'variable': 'C26',
        'block': 'C: accounts',
        'construct': 'has authorized a trusted contact',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual/account knowledge',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = does not know own account setup.',
    },
    {
        'variable': 'C41',
        'block': 'C: accounts',
        'construct': 'authorized trusted contact at account opening',
        'universally_asked': 'No — asked only if C26=1',
        'meaning_of_98': "Don't know/Don't recall",
        'dk_opportunity_type': 'recollection',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern; 98 also merges DK with "don\'t recall".',
    },
    {
        'variable': 'C42',
        'block': 'C: accounts',
        'construct': 'recalls being asked to name a trusted contact',
        'universally_asked': 'No — asked only if C26 in (2,98,99)',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern.',
    },
    {
        'variable': 'C43',
        'block': 'C: accounts',
        'construct': 'willing to name a trusted contact',
        'universally_asked': 'No — asked only if C26 in (2,98,99)',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern.',
    },
    {
        'variable': 'C7',
        'block': 'C: accounts',
        'construct': 'ever checked a regulator on a professional',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot recall.',
    },
    {
        'variable': 'D40',
        'block': 'D: markets/fraud',
        'construct': 'US markets are fair to all investors',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked 1-7 agreement item.',
    },
    {
        'variable': 'D31',
        'block': 'D: markets/fraud',
        'construct': 'worried about losing money to fraud',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked 1-7 agreement item.',
    },
    {
        'variable': 'D41',
        'block': 'D: markets/fraud',
        'construct': 'believes was targeted by fraud in past year',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot say whether targeted.',
    },
    {
        'variable': 'D42',
        'block': 'D: markets/fraud',
        'construct': 'lost money to the fraud',
        'universally_asked': 'No — asked only if D41=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (D41=1).',
    },
    {
        'variable': 'E2',
        'block': 'E: disclosure',
        'construct': 'ever received investment disclosures',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'recollection',
        'include': 'INCLUDE',
        'reason': 'Universally asked; DK = cannot recall.',
    },
    {
        'variable': 'E3',
        'block': 'E: disclosure',
        'construct': 'usual handling of disclosures',
        'universally_asked': 'No — asked only if E2=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (E2=1).',
    },
    {
        'variable': 'E4',
        'block': 'E: disclosure',
        'construct': 'perceived value of disclosures',
        'universally_asked': 'No — asked only if E2=1',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'EXCLUDE',
        'reason': 'Behind skip pattern (E2=1).',
    },
    {
        'variable': 'E6',
        'block': 'E: disclosure',
        'construct': 'preferred disclosure delivery method',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked preference item.',
    },
    {
        'variable': 'F30_1',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on personal financial professionals',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_2',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on brokerage research/tools',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_3',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on popular investments on a trading app',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_4',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on business/finance articles',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_5',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on TV programs',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_6',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on radio programs',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_7',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on online videos',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_8',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on podcasts',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_9',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on social media groups/message boards',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_10',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on paid newsletters/online resources',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F30_12',
        'block': 'F30 grid (11 rows)',
        'construct': 'reliance on friends, family, colleagues',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own reliance. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_1',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses YouTube for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_2',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Facebook for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_3',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Reddit for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_4',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses TikTok for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_5',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Instagram for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_6',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Twitter for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_7',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Discord for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_10',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses LinkedIn for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_40',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses WhatsApp for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_41',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Telegram for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F31_42',
        'block': 'F31 grid (11 rows)',
        'construct': 'uses Rumble for investing information',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot report own use. GRID — see battery weighting.',
    },
    {
        'variable': 'F40',
        'block': 'F: information',
        'construct': 'acts on social-media personality recommendations',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'behavioral self-report',
        'include': 'INCLUDE',
        'reason': 'Universally asked frequency item.',
    },
    {
        'variable': 'G2',
        'block': 'G: quiz/self-perception',
        'construct': 'self-assessed investing knowledge',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'EXCLUDE',
        'reason': 'Used as a model covariate elsewhere in the study; cannot also serve as an auxiliary control.',
    },
    {
        'variable': 'G30_1',
        'block': 'G30 grid (6 rows)',
        'construct': 'reason for investing: make money short term',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot place own motive. GRID — see battery weighting.',
    },
    {
        'variable': 'G30_2',
        'block': 'G30 grid (6 rows)',
        'construct': 'reason for investing: make money long term',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot place own motive. GRID — see battery weighting.',
    },
    {
        'variable': 'G30_3',
        'block': 'G30 grid (6 rows)',
        'construct': 'reason for investing: entertainment/excitement',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot place own motive. GRID — see battery weighting.',
    },
    {
        'variable': 'G30_4',
        'block': 'G30 grid (6 rows)',
        'construct': 'reason for investing: peers are doing it',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot place own motive. GRID — see battery weighting.',
    },
    {
        'variable': 'G30_5',
        'block': 'G30 grid (6 rows)',
        'construct': 'reason for investing: make a difference/values',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot place own motive. GRID — see battery weighting.',
    },
    {
        'variable': 'G30_6',
        'block': 'G30 grid (6 rows)',
        'construct': 'reason for investing: to learn about investing',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally administered grid row; DK = cannot place own motive. GRID — see battery weighting.',
    },
    {
        'variable': 'G31',
        'block': 'G: quiz/self-perception',
        'construct': 'importance of ESG in decisions',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked 1-10 importance item.',
    },
    {
        'variable': 'G40',
        'block': 'G: quiz/self-perception',
        'construct': 'parents held securities',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'factual knowledge about another person',
        'include': 'EXCLUDE',
        'reason': 'Used elsewhere in the study; 98 concerns knowledge of parents rather than of self.',
    },
    {
        'variable': 'G41',
        'block': 'G: quiz/self-perception',
        'construct': 'family talked about investing',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know/Don't recall",
        'dk_opportunity_type': 'recollection',
        'include': 'EXCLUDE',
        'reason': 'Used elsewhere in the study; 98 merges DK with "don\'t recall".',
    },
    {
        'variable': 'G42',
        'block': 'G: quiz/self-perception',
        'construct': "'people like me aren't usually investors'",
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'attitudinal/self-description',
        'include': 'INCLUDE',
        'reason': 'Universally asked 1-7 agreement item.',
    },
    {
        'variable': 'G43',
        'block': 'G: quiz/self-perception',
        'construct': 'would accept guaranteed 25% return',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'STUDY OUTCOME. Including the outcome in a control would guarantee an association.',
    },
    {
        'variable': 'G4',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G5',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G6',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G7',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G21',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G8',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G44',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G22',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G11',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G12',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G13',
        'block': 'G: quiz',
        'construct': 'financial-knowledge quiz item (11-item frozen battery)',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Quiz item; source of the predictor n_dk.',
    },
    {
        'variable': 'G23',
        'block': 'G: quiz',
        'construct': 'call-option bonus item',
        'universally_asked': 'Yes',
        'meaning_of_98': "Don't know",
        'dk_opportunity_type': 'n/a',
        'include': 'EXCLUDE',
        'reason': 'Bonus quiz item, excluded from the frozen 11-item battery by FINRA definition.',
    },
]


def _verify_round_trip():
    """Fail loudly if SPEC no longer reproduces the committed audit table."""
    from pathlib import Path
    import pandas as pd

    committed = Path(__file__).resolve().parent.parent / "docs" / "nonquiz-dk-item-audit.csv"
    if not committed.exists():
        return
    regenerated = pd.DataFrame(SPEC).to_csv(index=False)
    if regenerated != committed.read_text():
        raise RuntimeError(
            f"SPEC no longer reproduces {committed}.\n"
            "One of the two was edited independently. Reconcile them before "
            "running the sensitivity analysis."
        )


_verify_round_trip()
